recipe: default.v1

assistant_id: 20240805-155625-natural-limiter

language: en

pipeline:
- name: SingleStepLLMCommandGenerator
  llm:
    model_name: gpt-4
    request_timeout: 7
    max_tokens: 256

policies:
- name: FlowPolicy
- name: IntentlessPolicy
- name: EnterpriseSearchPolicy
  vector_store:
    type: "addons.faq.PostgresIR"

